### ISSUE TITLE
Trouble Running the scripts

### ISSUE THREAD

**Issue by stephen-carew** [KorigamiK/ultimate-batch-anime-downloader#10]
![Screenshot 2020-11-05 at 2 57 06 AM](https://user-images.githubusercontent.com/52305244/98156326-9a16f400-1f12-11eb-9f3d-73029c01b74f.png)

I can't seem to run any of the scripts. I get an error.

**Comment by KorigamiK** [comment]
Hmm, seems odd try to run this on the terminal
```pip install typing```
or try to use the version from the releases section at [here](https://github.com/KorigamiK/ultimate-batch-anime-downloader/releases)

**Comment by stephen-carew** [comment]
Tried the pip install typing, it installed with no problems then proceeded to attempt running the scripts.. didn't work.. downloaded the experimental version and tried running also.. didn't work too.. hahaha.. they both keep giving the same error. I thought maybe it just needs a reboot.. still nothing XD
![Screenshot 2020-11-05 at 3 13 30 AM](https://user-images.githubusercontent.com/52305244/98158087-5b366d80-1f15-11eb-8cf1-93af8d4a084d.png)


Unlucky I guess? :P

**Comment by EL-S** [comment]
I'm not completely sure but I believe type hinting only works in Python 3.5+(Although I see you tried 3.9?). Honestly, the code doesn't need them to run, so perhaps you can get away with removing the type hinting from the lines.

**Comment by stephen-carew** [comment]
I'll give it a shot

**Comment by EL-S** [comment]
This is possibly related but, type hinting on variables (not just parameters) was implemented in Python 3.6. Also, you should check the version of Python you are running the script with. Try something like Python -V

https://stackoverflow.com/questions/42002596/python-3-5-typed-namedtuple-syntax-produces-syntaxerror

**Comment by stephen-carew** [comment]
son of a gun. Im running python 2.7 XD

**Comment by EL-S** [comment]
No worries, it's common to have path/env vars set to the correct version of pip but incorrect version of Python :)

**Comment by stephen-carew** [comment]
Yep. if I run the command using python3 downloader.py it works perfectly fine! Thanks so much!!

**Comment by KorigamiK** [comment]
Heyy! nice.
