### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by thaynos** [KorigamiK/ultimate-batch-anime-downloader#11]
took me a while to get the app running
i was so happy when it got the download links
but then this happens 😢 
![image](https://user-images.githubusercontent.com/83282129/119388008-c93c5980-bcda-11eb-96bd-3f291da3b01a.png)
aw man i hope the dev dint stop maintaining this repo

**Comment by ArjixWasTaken** [comment]
Well, he mostly works on this
https://github.com/KorigamiK/kickassanime-downloader
And also the last commit to this repo was 7 months ago.
PS: I would make a PR to fix the code, but I cba to do that, I'm too lazy.

~~If you don't want kickassanime then you can instead use https://github.com/anime-dl/anime-downloader~~

**Comment by KorigamiK** [comment]
That is correct but I won't want to work on this project now that I've seen that Gogoanime cdn has captcha on some of its shows.
But I've updated the script to just be barely usable using Gogoanime. Yugenanime is deprecated.

 You should be able to get it working right now but I also suggest you to look into [kickassanime-downloader](https://github.com/KorigamiK/kickassanime-downloader) It doesn't have an option to download from the Cogoanime servers but you can use it to stream them. Maybe I'll also add the option to download them also.

I've also updated the readme a little so have a look at that too.

**Comment by KorigamiK** [comment]
I forgot to mention the [release](https://github.com/KorigamiK/ultimate-batch-anime-downloader/releases/tag/3.6) . Check if it works for now. I'll leave it to Arjix to decide if this issue should be closed.

**Comment by thaynos** [comment]
it doesnt work at all now
![image](https://user-images.githubusercontent.com/83282129/119462961-540c6b00-bd52-11eb-966c-621ccfa4cded.png)
ig ill use the kickassnaime downlaoder

**Comment by thaynos** [comment]
it doesnt show the anime list

**Comment by KorigamiK** [comment]
You should see the anime when you search just `taizai`. If you are not able to get a show using the search feature, you can always pass it a url from Gogoanime website.

**Comment by ArjixWasTaken** [comment]
> I forgot to mention the [release](https://github.com/KorigamiK/ultimate-batch-anime-downloader/releases/tag/3.6) . Check if it works for now. I'll leave it to Arjix to decide if this issue should be closed.

Yeah, the kickassanime-downloader looks better to me, so I see no point in working on this anymore.
I might make a PR at some point to fix the error (+make some aesthetic changes)
But that won't be anytime soon.

EDIT: Oh, you already fixed the error.
