### ISSUE TITLE
When trying to select quality number: "Enter correct option in range!"

### ISSUE THREAD

**Issue by AnimeniacSimey** [KorigamiK/ultimate-batch-anime-downloader#12]
I'm trying to download something and when it gives me the option to choose the quality, 2 abnormal things happen: 

1. It doesn't list the qualities and what numbers they're associated with, as it did before.
2. I just thought to go with the highest so I inputted "3" and it just says "Enter correct option in range !"

Can somebody help me with this, please? Thank you!

**Comment by KorigamiK** [comment]
Yes, it might not work correctly now as it is not maintained currently. I can only suggest you to check for any updates but if you are on the latest version then I advise you to take a look into [kickassanime downloader](https://github.com/KorigamiK/kickassanime-downloader). 

It is actively maintained and works as intended. I have tried to document installation and usage pretty extensively. If you are not able to use it feel free to make a new issue there, I'll help you install it. You won't be disappointed.

**Comment by AnimeniacSimey** [comment]
Thank you!
